#!/bin/sh

if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS=$NAME
elif type lsb_release >/dev/null 2>&1; then
  OS=$(lsb_release -si)
elif [ -f /etc/lsb-release ]; then
  . /etc/lsb-release
  OS=$DISTRIB_ID
elif [ -f /etc/debian_version ]; then
  OS=Debian
else
  OS=$(uname -s)
fi

unset GIT_DIR

msg() {
  printf "\e[1m$1\e[m\n"
}

install_brew() {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  if [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  fi
}

# Install package manager
if [ "$OS" = "Darwin" ]; then
  if ! command -v brew >/dev/null 2>&1; then
    msg "Installing homebrew"
    install_brew
  fi
  pkgmgr="brew install"
elif command -v apt-get >/dev/null 2>&1; then
  if [ $(id -u) -eq 0 ]; then
    pkgmgr="apt-get update; apt-get -y install"
  else
    pkgmgr="sudo -E apt-get update; sudo -E apt-get -y install"
  fi
elif command -v apk >/dev/null 2>&1; then
  if [ $(id -u) -eq 0 ]; then
    pkgmgr="apk add --no-cache"
  else
    pkgmgr="sudo -E apk add --no-cache"
  fi
elif command -v dnf >/dev/null 2>&1; then
  if [ $(id -u) -eq 0 ]; then
    pkgmgr="dnf install -y"
  else
    pkgmgr="sudo -E dnf install -y"
  fi
else
  pkgmgr=""
fi

# Install deps
deps=""
if ! command -v git >/dev/null 2>&1; then
  deps=$deps" git"
fi
if ! command -v yadm >/dev/null 2>&1; then
  deps=$deps" yadm"
fi
if [ -n "$deps" ]; then
  if [ -n "$pkgmgr" ]; then
    msg "The following packages will be installed:$deps"
    printf "Press \e[1mRETURN\e[m/\e[1mENTER\e[m to continue or ctrl-c to abort: "
    read c
	for dep in $deps; do
      eval $pkgmgr $dep
	done
  else
    msg "Package maneger was not found." 1>&2
    msg "Install$deps manually." 1>&2
    exit 1
  fi
fi

deps=""
if ! command -v git >/dev/null 2>&1; then
  deps=$deps" git"
fi
if ! command -v yadm >/dev/null 2>&1; then
  deps=$deps" yadm"
fi
if [ -n "$deps" ]; then
  msg "Cannot install$deps via default package manager"
  printf "Press \e[1m1\e[m to install yadm via homebrew or \e[1m2\e[m to download yadm script or ctrl-c to abort: "
  read c
  if [ "${c}" = 1 ]; then
    msg "Installing homebrew"
    install_brew
    msg "Installing$deps"
    eval brew install$deps
  elif [ "${c}" = 2 ]; then
    msg "Downloading yadm"
    if [ $(id -u) -eq 0 ]; then
      curl -fLo /usr/local/bin/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm && chmod a+x /usr/local/bin/yadm
	else
	  sudo curl -fLo /usr/local/bin/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm && sudo chmod a+x /usr/local/bin/yadm
	fi
  else
	exit 1
  fi
fi

# Clone repository
if [ ! -d ~/.local/share/yadm/repo.git ]; then
  msg "Cloning repository"
  yadm clone --no-bootstrap "https://github.com/rtks/dotfiles.git"
fi

# Bootstrap fish
if command -v fish >/dev/null 2>&1; then
  msg "Bootstraping fish"
  fish -c 'set_color_custom; set -U fish_greeting "";'

  # Install fisher
  if [ ! -f ~/.config/fish/functions/fisher.fish ]; then
    msg "Installing fisher"
    fish -c "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
  fi
  msg "Bootstraping fisher"
  fish -c "fisher update"
fi

# Bootstrap tmux
if command -v tmux >/dev/null 2>&1; then
  if [ ! -f ~/.tmux/plugins/tpm/tpm ]; then
    msg "Installing Tmux Plugin Manager"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  fi
  msg "Bootstraping Tmux Plugin Manager"
  ~/.tmux/plugins/tpm/scripts/install_plugins.sh
fi

# Bootstrap vim
if command -v vim >/dev/null 2>&1; then
  # Install vim-plug
  if [ ! -f ~/.vim/autoload/plug.vim ]; then
    msg "Installing vim-plug"
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi
  msg "Bootstraping vim-plug"
  vim +'PlugInstall --sync' +qa </dev/tty
fi
