code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension deerawan.vscode-dash
code --install-extension dunstontc.viml
code --install-extension eamodio.gitlens
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension Gruntfuggly.activitusbar
code --install-extension jebbs.plantuml
code --install-extension johnstoncode.svn-scm
code --install-extension kexi.vscode-uiflow
code --install-extension lunaryorn.fish-ide
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-dotnettools.csharp
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.sublime-keybindings
code --install-extension mshr-h.veriloghdl
code --install-extension mushan.vscode-paste-image
code --install-extension rust-lang.rust
code --install-extension shardulm94.trailing-spaces
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sidneys1.gitconfig
code --install-extension skyapps.fish-vscode
code --install-extension vadimcn.vscode-lldb
code --install-extension william-voyek.vscode-nginx
code --install-extension vscode.theme-solarized-light-highcontrast
code --install-extension yzhang.markdown-all-in-one