add_newline = false
command_timeout = 10000

format = '$git_status'

[git_status]
format = '$ahead_behind(|[$all_status]($style))'
style = "cyan"
conflicted = '[!$count](bold red)'
deleted = '[×$count](red)'
renamed = '[⇄$count](red)'
modified = '[+$count](red)'
untracked = '[…$count](bold blue)'
staged = '[✓$count](green)'
stashed = '[≡$count]($style)'
ahead = '[⤴$count](blue)'
behind = '[⤵$count](blue)'
diverged = '[⤵$behind_count⤴$ahead_count](blue)'
