add_newline = false
command_timeout = 5000

# Which is equivalent to
format = """
${env_var.FISH_PROMPT_EXTRA}\
$hostname\
$localip\
$os\
$container\
$shell\
$shlvl\
$singularity\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
(\\($git_branch\
$git_commit\
${env_var.FISH_PROMPT_GIT}\
$git_state\\) )\
$hg_branch\
$pijul_channel\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$character"""

[username]
disabled = true

[battery]
disabled = true

[hostname]
format = "[$hostname]($style) "
style = "bright black"

[container]
format = '[$symbol $name]($style) '

[shell]
disabled = false
format = '[$indicator]($style)'
style = 'blue'
fish_indicator = ''
bash_indicator = 'bash '
zsh_indicator = 'zsh '
powershell_indicator = 'PS '

[directory]
style = "green"
fish_style_pwd_dir_length = 1

[git_branch]
format = '[$branch]($style)'
style = "green"

[git_commit]
format = '[\($hash$tag\)]($style)'
style = "green"

[git_state]
format = '(|[$state($progress_current/$progress_total)]($style))'
style = "bright-black"

[character]
success_symbol = "[>](black)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[>](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
min_time = 500

[status]
disabled = false
format = '[$status(\($common_meaning$signal_name\))]($style) '
pipestatus = true
pipestatus_separator = ""
pipestatus_format = '$pipestatus'

[env_var.FISH_PROMPT_GIT]
format = '[$env_value](black)'

[env_var.FISH_PROMPT_EXTRA]
format = "[$env_value](black)\n"
