add_newline = false
command_timeout = 10000

format = '\($git_branch$git_commit$git_status$git_state\) '

[git_branch]
format = '[$branch]($style)'
style = "green"

[git_commit]
format = '[\($hash$tag\)]($style)'
style = "green"

[git_status]
format = '$ahead_behind(|[$all_status]($style))'
style = "cyan"
conflicted = '[!$count](bold red)'
deleted = '[×$count](red)'
renamed = '[⇄$count](red)'
modified = '[+$count](red)'
untracked = '[…$count](bold blue)'
staged = '[✓$count](green)'
stashed = '[≡$count]($style)'
ahead = '[⤴$count](blue)'
behind = '[⤵$count](blue)'
diverged = '[⤵$behind_count⤴$ahead_count](blue)'

[git_state]
format = '(|[$state( $progress_current/$progress_total)]($style))'
style = "bright-black"
