add_newline = false
command_timeout = 10000

format = '$git_status'

[git_status]
format = '$ahead_behind(|$staged$conflicted$deleted$renamed$modified$typechanged$untracked$stashed)'
ahead = '[⤴$count](cyan)'
behind = '[⤵$count](cyan)'
diverged = '[⤵$behind_count⤴$ahead_count](cyan)'
staged = '[✓$count](green)'
conflicted = '[!$count](bold red)'
deleted = '[×$count](red)'
renamed = '[→$count](red)'
modified = '[+$count](red)'
typechanged = '[^$count](red)'
untracked = '[…$count](blue)'
stashed = '[≣$count](bright-blue)'
