#!/bin/bash

system_type=$(uname -s)
unset GIT_DIR

# Install package manager
if [ "$system_type" = "Darwin" ]; then
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
  pkgmgr=brew
elif command -v apt >/dev/null 2>&1; then
  pkgmgr="sudo -E apt"
else
  echo "Package maneger was not found." 1>&2
  exit 1
fi

# Install yadm
if ! command -v yadm >/dev/null 2>&1; then
  echo "Installing yadm"
  $pkgmgr install yadm
fi

# Clone repository
if [ ! -d ~/.yadm/repo.git ]; then
  echo "Cloning repository"
  yadm clone --no-bootstrap "https://github.com/rtks/dotfiles.git"
fi

# Install fish
if ! command -v fish >/dev/null 2>&1; then
  echo "Installing fish"
  if [[ $pkgmgr =~ apt ]]; then
    $pkgmgr-add-repository ppa:fish-shell/release-3
    $pkgmgr update
  fi
  $pkgmgr install fish
fi

# Install fisher
if [ ! -f ~/.config/fish/functions/fisher.fish ]; then
  echo "Installing fisher"
  curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
fi
fish -c fisher

# Install vim-plug
if [ ! -f ~/.vim/autoload/plug.vim ]; then
  echo "Installing vim-plug"
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim +'PlugInstall --sync' +qa -

